## Basic Configuration

baseurl = "https://shenoybr.github.io/hugo-goa-demo/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Vlad Duda"
title = "Vlad Duda"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "vlad-duda" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Vlad Duda"
intro = "Startup Guru Extraordinaire"
description = "Now @Pied Piper. Previously @Hacker Hostel, @Bachmanity and @Aviato. <br/> \"What is F times 5? It's Fleventy-five.\""
authorimage = "portrait.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "Vduda"
# instagram = "<username>"
# xing = "<username>"
linkedin = "vduda"
twitter = "BigBostonGuy"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
email = "vlad.duda.slack@gmail.com"

## Extras
[params.extra]
copyright = "© 2017. Vlad Duda. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
# [[menu.main]]
#     name = "blog"
#     weight = 100
#     identifier = "blog"
#     url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 300
    url = "/resume/"