## Basic Configuration
baseurl = 'https://vlad-duda.com'
builddrafts = false
canonifyurls = false
languageCode = 'en-US'

contentdir = 'content'
layoutdir = 'layouts'
publishdir = 'public'

author = 'Vlad Duda'
title = 'Vlad Duda'

theme = 'hugo-goa'

## Hugo Built-in Features
#disqusShortname = 'vlad-duda' # Comment out to disable Disqus.
googleAnalytics = 'UA-61576514-1'
enableRobotsTXT = true

## Site Settings
[params]
author = 'Vlad Duda'
intro = 'Pragmatist'

# description = """
# Now <a href='https://rit.rakuten.co.jp'>@Rakuten</a>, 
# Previously <a href='https://maxwellhealth.com'>@MaxwellHealth</a>, 
# <a href='https://nuodb.com'>@NuoDB</a> and <a href='https://TheLightWalk.com'>@TheLightWalk</a>. 
# <br/> \"Simplicity is the ultimate sophistication.\"
# """
authorimage = 'portrait.jpg'
dateformat = 'Jan 2, 2006'

## Site Meta Settings
[params.meta]
description = 'Simple minimalist Vlad Duda'
keywords = 'minimalist,vlad,duda,blog,goa,hugo,pragmatist'

## Social Accounts
[params.social]
github = 'Vduda'
# instagram = '<username>'
# xing = '<username>'
linkedin = 'vduda'
twitter = 'BigBostonGuy'
#facebook = '<username>'
#google = '<username>'
#stackoverflow = '<username>'
email = 'vlad.duda@outlook.com'

## Extras
[params.extra]
copyright = '© 2022. Vlad Duda. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/).' 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = 'Book a Meeting'
    identifier = 'meeting'
    weight = 100
    url = 'https://calendly.com/vlad-duda/30min'
[[menu.main]]
    name = 'Reading DB'
    identifier = 'books'
    weight = 200
    url = 'https://docs.google.com/spreadsheets/d/13f8iDJDGdD8f8blAMoJfE5ofbr4PyAroc4fmHpjCRPs/edit?usp=sharing'
[[menu.main]]
    name = 'Github'
    identifier = 'github'
    weight = 300
    url = 'https://github.com/VDuda'
[[menu.main]]
    name = 'ideas'
    weight = 400
    identifier = 'ideas'
    url = '/ideas/'
[[menu.main]]
    name = 'projects'
    weight = 500
    identifier = 'projects'
    url = '/projects/'
