baseURL = "http://vlad-duda.me"
languageCode = "en-us"
title = "Meet Vlad Duda"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Vlad Duda"
    description = "Simple at the Core"
    email = "Vlad.Duda.Slack@gmail.com"
    phone = "+1(857) 323-2755"
    address = "PO BOX 52573, Boston MA "
    year = 2017
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "resume"
    url = "/resume/"
    weight = 5

[params.disqus]
    site = "vlad-duda"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-61576514-1"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/BigBostonGuy"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/vduda"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
  title = "github"
  url = "https://github.com/VDuda"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
  title = "email"
  url = "mailto:Vlad.Duda.Slack@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"